# Site Settings
title: Ikenna M. D. Nwankwo
description: Website showcasing Data Analytics, Research, and Business Strategy Projects by Ikenna M. D. Nwankwo.
logo: /assets/head_shot.webp

# Host Configuration
url: "https://nmartin169.github.io"
baseurl: "/webportfolio"

# Build Theme & Plugins
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
